[custom.all.scgi]
type   = "local"
path   = "."
ipkg   = "scgi.ipkg"

[custom.all.scgi-example]
type   = "local"
path   = "example"
ipkg   = "scgi-example.ipkg"

[custom.all.http-types]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-http-types.git"
commit = "latest:main"
ipkg   = "http-types.ipkg"

[custom.all.http-server-api]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-http-types.git"
commit = "latest:main"
ipkg   = "http-server-api/http-server-api.ipkg"
