[custom.all.scgi]
type   = "local"
path   = "."
ipkg   = "scgi.ipkg"

[custom.all.scgi-example]
type   = "local"
path   = "example"
ipkg   = "scgi-example.ipkg"

[custom.all.bytestring]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-bytestring"
commit = "latest:main"
ipkg   = "bytestring.ipkg"
